name: CI

on: [ push, pull_request ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install npm deps
      working-directory: ./test
      run: npm ci
    # For some reason installing the rust toolchain via wasm-pack leads to CI failures.
    # This will read the top level rustup-toolchain.toml and install the required stuff.
    - name: Trigger toolchain installation
      working-directory: ./test
      run: cargo fetch
    - name: Run tests
      working-directory: ./test
      run: npm test
