name: Demo

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        # For some reason installing the rust toolchain via wasm-pack leads to CI failures.
    # This will read the top level rustup-toolchain.toml and install the required stuff.
    - name: Trigger toolchain installation
      working-directory: ./demo
      run: cargo fetch
    - name: Build demo
      working-directory: ./demo
      run: |
        npm ci
        npm run build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: demo/dist # The folder the action should deploy.
